name: "Dry-build NixOS"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v26
      - name: Dry-build mystix
        run: nix run nixpkgs#nixos-rebuild -- dry-build --flake .#mystix
      - name: Dry-build regis
        run: nix run nixpkgs#nixos-rebuild -- dry-build --flake .#regis
